# Generated by Django 5.0.1 on 2024-01-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_interest_remove_person_age_person_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='interests',
        ),
        migrations.AddField(
            model_name='interest',
            name='persons',
            field=models.ManyToManyField(related_name='persons', to='app.person'),
        ),
    ]
